//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BushmelevExamen.DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductRelationsView
    {
        public string Article { get; set; }
        public int NameID { get; set; }
        public int UnitID { get; set; }
        public int CategoryID { get; set; }
        public int SupplierID { get; set; }
        public int ManufacturerID { get; set; }
        public string Name { get; set; }
        public string Unit { get; set; }
        public string Category { get; set; }
        public string Supplier { get; set; }
        public string Manufacturer { get; set; }
    }
}
